Added tabIndex parameter to dialog buttons
ciena-frost/ember-frost-modal pull request #60
Opened 2016-11-14 18:43 UTC by TheOtherDude

### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #patch# - backwards-compatible bug fix
 - [x] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG
* Added tabIndex parameter to dialog buttons
* Gave cancel button a default tabIndex of 1 so that it comes after confirm button in tab order

2016-11-14 18:49 UTC, ember-cli-visual-acceptance commented
# Visual Acceptance tests:
### No changes

2016-11-14 19:46 UTC, rox163 commented on addon/templates/components/frost-modal-dialog.hbs
> +      tabIndex=(ifUndefined button.tabIndex 1 button.tabIndex)
it seems this would give all custom buttons a tabIndex of 1 if that prop is undefined?

2016-11-14 19:51 UTC, TheOtherDude commented on addon/templates/components/frost-modal-dialog.hbs
> +      tabIndex=(ifUndefined button.tabIndex 1 button.tabIndex)
Oops, good catch!

2016-11-15 13:49 UTC, sglanzer-fire requested changes
Let's confirm if the new helper is necessary

2016-11-15 13:49 UTC, sglanzer commented on addon/templates/components/frost-modal-dialog.hbs
> +    tabIndex=(ifUndefined params.cancel.tabIndex 1 params.cancel.tabIndex)
Can we just use the standard if where undefined would evaluate to falsey?

2016-11-15 13:49 UTC, sglanzer commented on addon/helpers/if-undefined.js
> +export default Ember.Helper.helper(ifUndefined);
If we decide this helper is necessary (see below) - I would still like it to come from `core`

2016-11-15 16:13 UTC, TheOtherDude commented on addon/templates/components/frost-modal-dialog.hbs
> +    tabIndex=(ifUndefined params.cancel.tabIndex 1 params.cancel.tabIndex)
Unfortunately, that would mean that a defined tabIndex of zero would be ignored as if it were undefined.

2016-11-15 16:15 UTC, TheOtherDude commented on addon/helpers/if-undefined.js
> +export default Ember.Helper.helper(ifUndefined);
Do I need to do anything besides add the helper to `ember-frost-core`?

2016-11-15 16:16 UTC, sglanzer commented on addon/templates/components/frost-modal-dialog.hbs
> +    tabIndex=(ifUndefined params.cancel.tabIndex 1 params.cancel.tabIndex)
Chuck an `(or` in as well?

2016-11-15 16:18 UTC, sglanzer commented on addon/templates/components/frost-modal-dialog.hbs
> +    tabIndex=(ifUndefined params.cancel.tabIndex 1 params.cancel.tabIndex)
`(if (or params.cancel.tabIndex (eq params.cancel.tabIndex 0) params.cancel.tabIndex 1)` I think...

2016-11-15 16:23 UTC, sglanzer commented on addon/templates/components/frost-modal-dialog.hbs
> +    tabIndex=(ifUndefined params.cancel.tabIndex 1 params.cancel.tabIndex)
Sorry, I just want to avoid a helper if possible

2016-11-15 16:36 UTC, TheOtherDude commented
Removed `ifUndefined` helper. Thanks for the tip @sglanzer

2016-11-15 16:41 UTC, sglanzer commented
Glad it worked!  Thanks for making the change 👍

2016-11-15 16:41 UTC, sglanzer commented
Approved

2016-11-15 17:16 UTC, merged