add classmodifier to modal content
ciena-frost/ember-frost-modal pull request #70
Opened 2016-12-14 15:38 UTC by rox163

### This project uses [semver](semver.org), please check the scope of this pr:
 - [x] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG
**adding** a classModifier for the contained modal.

2016-12-14 15:46 UTC, ember-cli-visual-acceptance commented
# Visual Acceptance tests:
### No changes

2016-12-14 16:04 UTC, sglanzer commented
Sorry, I know I said this would be quick, but would you mind adding a test just to demonstrate that the modifier hits the right part of the DOM?

2016-12-14 20:17 UTC, sglanzer commented on addon/components/dialogs/form.js
> -      classModifier: 'form',
I don't mind leaving this in (in case anyone is using it already)

2016-12-14 20:18 UTC, sglanzer-fire requested changes
I'd put the classModifier for form back, otherwise this is great, thanks!

2016-12-15 14:33 UTC, sglanzer commented
Approved

2016-12-15 14:33 UTC, merged